### ISSUE TITLE
Reboot every 15 min - Memory leak

### ISSUE THREAD

**Issue by erik73** [johannyren/PowerDisplayESPHome#3]
Hi.

First of all, tanks for the great work you have put into this!

I have come to the conclusion that the reboot approx. every 15 minutes is due to the ESP32 running out of memory. 
I am not sure why, but here is a screenshot that shows what is happening.

Any ideas?

![image](https://github.com/johannyren/PowerDisplayESPHome/assets/9859151/5874813c-1b28-4d96-bab7-862377cab5ca)

**Comment by johannyren** [comment]
Thanks a lot for pointing this out. I have fixed the problem - it's in the lambda, as it created a new class instance every time it was executed. It is now running stable.
Yaml file has been updated with the fix.

![image](https://github.com/johannyren/PowerDisplayESPHome/assets/76902723/fdad3f72-ed62-43e9-bdc1-780bf240ede3)

**Comment by erik73** [comment]
Well done!

Thanks for fixing this.
