### ISSUE TITLE
Reset the cost scale on the display

### ISSUE THREAD

**Issue by LarsBorris** [johannyren/PowerDisplayESPHome#4]
Hello!

Great project! I have it running with a "clone" of nordpool called energidata service.
Everything is displayed fine except for the cost scale.
Is there a way to reset this or somehow make it work with energidata service?

See image
![display](https://github.com/johannyren/PowerDisplayESPHome/assets/10630935/111c5139-922f-4025-8b85-ea1f4719c024)

Thanks!

**Comment by johannyren** [comment]
Do you get a value from energidata for the Max price (per day)?

The display expects to get this data from nordpool, as of below:

     powerDisplay.SetTodayMaxPrice(id(nordpool_max).state);

If this value is not set, the display will default to 42, which would explain the cost scale being out of proportion. If you don't get this value, you could enter a fixed value instead, but that's less desirable.

**Comment by johannyren** [comment]
Adding to this... I checked the Energidataservice plug in, and it seems it gives you a value from the variable "today_max". Try using this as of above.
