### ISSUE TITLE
Graph start time

### ISSUE THREAD

**Issue by Spangsberg** [johannyren/PowerDisplayESPHome#5]
Hi Johnny

I have used your repository to create a display suiting my needs, but there is one thing I can't figure out...

![IMG_7891](https://github.com/johannyren/PowerDisplayESPHome/assets/58219639/749f2095-11e9-4266-8faf-9c5f7df0662c)

When tomorrow's prices are known, how do I get the graph to show prices starting now'ish and 18-20 hours into the future. Showing the prices that have been today doesn't really bring me any value....

Thank you for a great repo.
/Dennis

**Comment by johannyren** [comment]
Hi Dennis,

Nordpool releases tomorrow’s prices around 13:00 so it’s difficult to have
a well working rolling curve. But you could update the array received from
nordpool after 13:00 so it will display the next 24 hours or so then.
Alternatively, you could use the tomorrow’s prices to draw a second curve,
perhaps in a different colour.

If you create something useful then don’t hesitate to create a fork and
upload your version!

Best regards,
Johan

ons 29 nov. 2023 kl. 21:10 skrev Spangsberg ***@***.***>:
