### ISSUE TITLE
Request for line thickness

### ISSUE THREAD

**Issue by flix4f** [johannyren/PowerDisplayESPHome#6]
My Esphome knowledge is not great enough to be able to change the thickness of the price line in the graph. But with the current thickness it is hard to see the line from a distance. 
where/how could this line thickness be changed?

**Comment by galvheim** [comment]
Agreed. THis would be nice to set. Now its hardly visible

**Comment by galvheim** [comment]
Hi,

Found a way: 
On line 274 of the power_display.h file. Add this line under it. That will just copy the line and and scew it by one pixel up, thus doubling it the thickness.

`buff->line(xPos + x1*xFactor, yPos+1+graphHeight-(y1*yFactor), xPos + x2*xFactor, yPos+graphHeight-(y2*yFactor), color);`
Then add this under there again, doubling it once more: 
`buff->line(xPos + x1*xFactor, yPos+2+graphHeight-(y1*yFactor), xPos + x2*xFactor, yPos+2+graphHeight-(y2*yFactor), color);`

REMEMBER to flush build files before compiling again...

**Comment by sturlahallas** [comment]
There is a slight mistake here. Should be: buff->line(xPos + x1*xFactor, yPos+1+graphHeight-(y1*yFactor), xPos + x2*xFactor, yPos**+1**+graphHeight-(y2*yFactor), color);

**Comment by galvheim** [comment]
Ok. It still compiles ok, and give the result I am after with triple line thickness. What result does yours give?

**Comment by johannyren** [comment]
I agree it increases visibility. 
Included in latest power_display.h.
