### ISSUE TITLE
Current consumption is not updating but pulling nicely from sensor according to logs

### ISSUE THREAD

**Issue by galvheim** [johannyren/PowerDisplayESPHome#8]
Hi,

The LOG from the POwerDisply shows that import_el is pulling sensor data nicely from the pulsemeter-sensor I have. (entity_id: sensor.glowpress_glowpress_power_consumption), but no matter what I do, there is no update in the display. It only says 42 W.
[logs_spotpris-display_logs.txt](https://github.com/johannyren/PowerDisplayESPHome/files/15221271/logs_spotpris-display_logs.txt)
![Skjermbilde 2024-05-06 151621](https://github.com/johannyren/PowerDisplayESPHome/assets/132774949/b8e4e5ce-8951-447f-97ce-24fd03a1a709)
What can be wrong here?

**Comment by Njamotep** [comment]
I have the same issue. Only showing 42W, Accumulated 42KWh and 42kr/kWh. Total cost of 1764kr. Can't figure it out.

**Comment by galvheim** [comment]
Hi,
Most likely you have not gone to Configuration for you ESPHome Device and set i t to "Allow the device to make service calls..."

After doing that it should work. 


![Screenshot_20240513_182613_Home Assistant](https://github.com/johannyren/PowerDisplayESPHome/assets/132774949/003ed34f-cc2a-42fe-b0f5-07357b9d2acb)
nfigu

**Comment by Njamotep** [comment]
Success! Thank you! 🥳
